[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiogram>=3.22.0",
    "openai>=1.101.0",
    "python-dotenv>=1.1.1",
    "pytest>=8.3.2",
    "pytest-asyncio>=0.23.8",
]
